### ISSUE TITLE
Profile e not outputting any info.

### ISSUE THREAD

**Issue by SimplyLime** [MinimallyCorrect/TickProfiler#101]
so I'm having issues with tickprofiler on my 1.12.2 server running sponge with the continuum modpack. Running profile e yields the result shown.

https://gyazo.com/82334743bdb79b68ca3e0ff1660748b7

**Comment by JaSpr** [comment]
We are having the same issue.  Nothing in the logs indicates a problem with profiling, but when we run /profile e 10, we get the following response: ([screenshot](https://i.imgur.com/XbjvTmc.png)).

**Comment by LunNova** [comment]
I'll have a look at both of these on Wednesday.

**Comment by badgernz** [comment]
Any Progress on this?
I am also having the same issue on my Continuum, Sevtech and Revelations servers.
Running Sponge spongeforge-1.12.2-2705-7.1.0-BETA-3364 & Tried both TickProfiler-1.12-0.0.4 & TickProfiler-1.12-0.0.2

**Comment by Magi1053** [comment]
I see that there is now a beta release on curseforge for 1.12.2. However I tried downloading that version and this bug still exists.

**Comment by LunNova** [comment]
May be caused by an incompatibility with VanillaFix

**Comment by LunNova** [comment]
Fixed now... Good thing I didn't specify which Wednesday it'd get fixed on or I'd be extremely late. 🤔

**Comment by jinkhya** [comment]
I just tried that version with my custom modpack and I'm still having an empy /profile e empty sadly :(
I tried forge 2759, tickprofiler 0.0.7 and vanillafix1.0.9-97 and it works fine so it must be something else in my pack still breaking it. It doesn't work on Sevtech either.
