### ISSUE TITLE
Tickprofiler #26 Not working on Sponge for 1.8.9

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickProfiler#47]
Hello Nallar!

The title is a short description but below are the specifics:

Forge Version: forge-1.8.9-11.15.1.1902-1.8.9-universal
Sponge Version: spongeforge-1.8.9-1890-4.2.0-BETA-1443
Tickprofiler Version:TickProfiler-1.8.9.jenkins.24

Sample Image: http://i.imgur.com/EkW94eS.png

Log: http://pastebin.com/ZWnSG6X9

Please let me know if you need anything else! :)

**Comment by LunNova** [comment]
Should be fixed in commit f70e8996ee67271e060.

Can you grab the latest TickProfiler build and confirm? Thanks

**Comment by helkarakse** [comment]
Hi there Nallar, we're currently on latest TickProfiler build 32 and we're still not getting any results in the entity list. There are no errors reported by forge/sponge in the logs.

http://i.imgur.com/XLvwyVJ.png

**Comment by LunNova** [comment]
Can you upload `fml-server-latest.log`? I'm specifically interested in any lines including `[ModPatcher/]`, but the entire log may be useful.

**Comment by helkarakse** [comment]
It's certainly running the updated version of ModPatcher, v90 I believe. The log file is far too large to post on pastebin, so here it is on our download section: http://atlas.otegamers.com/pioneers-fml-server-latest.log

**Comment by LunNova** [comment]
The ModPatcher version is okay. I'm not sure why that hasn't worked.

The lines:

```

[18:20:37] [main/TRACE] [JavaPatcher/]: Patching net.minecraft.world.WorldServer with clone(deobf:net.minecraft.world.WorldServer/updateEntities,to:updateEntities_withProfiling) {func_72939_s()V}
[18:20:37] [main/TRACE] [JavaPatcher/]: Patching net.minecraft.world.WorldServer with insertCodeBefore(deobf:net.minecraft.world.WorldServer/updateEntities) {func_72939_s()V}
[18:20:38] [main/TRACE] [JavaPatcher/]: Patching net.minecraft.world.WorldServer with replaceMethodCall(deobf:net.minecraft.world.WorldServer/updateEntities_withProfiling,method:func_73660_a) {updateEntities_withProfiling()}
[18:20:38] [main/TRACE] [JavaPatcher/]: Replaced call to net.minecraft.util.ITickable/func_73660_a in net.minecraft.world.WorldServer.updateEntities_withProfiling()
[18:20:38] [main/TRACE] [JavaPatcher/]: Replaced call to net.minecraft.util.ITickable/func_73660_a in net.minecraft.world.WorldServer.updateEntities_withProfiling()
[18:20:38] [main/TRACE] [JavaPatcher/]: Patching net.minecraft.world.WorldServer with replaceMethodCall(deobf:net.minecraft.world.WorldServer/updateEntities_withProfiling,method:func_72870_g) {updateEntities_withProfiling()}
[18:20:38] [main/TRACE] [JavaPatcher/]: Replaced call to net.minecraft.world.WorldServer/func_72870_g in net.minecraft.world.WorldServer.updateEntities_withProfiling()
```

Show up in your log, so the patches appear to be applying correctly.

Can you try the latest TickProfiler again (now .35), and add the following to your server launch options before the `-jar`:

`-Dnallar.LaunchClassLoaderUtil.dumpTransformers=true -Dnallar.ModPatcher.dump=true`

This will cause it to log the transformers which are currently in use. It will also dump transformed minecraft server classes in the `DUMP/` folder in your server directory. If you could upload the files `net.minecraft.world.WorldServer_unpatched.class` and `net.minecraft.world.WorldServer.class`, I can check what the patch actually did.

**Comment by helkarakse** [comment]
Hey, sorry it took a while to get back to you. The two files are here: http://atlas.otegamers.com/net.minecraft.world.WorldServer.class and http://atlas.otegamers.com/net.minecraft.world.WorldServer_unpatched.class

**Comment by LunNova** [comment]
Good news, [it looks patched correctly.](https://gist.github.com/nallar/c24c9dec03db8c4fddbe822066ffee88)

Bad news, I have no idea why it's not working. :( You do actually have loaded and ticking entities when you're running it?

If there aren't any players online there's no guarantee anything's actually running due to sponge's activation range settings.

**Comment by helkarakse** [comment]
Haha, you know what. I forgot about that. Let me get on and run the command in person, sorry.

Edit:

Looks like it's working perfectly now. http://i.imgur.com/OLcfJhU.png. Do you want to release another build that doesn't have the DUMP folder, or will removing the java parameters prevent the DUMP folder from being created?

**Comment by LunNova** [comment]
Remove the parameters and delete the folder, no need for a new build. Are you with the same group as @AuricPolaris and I can close this issue now?

**Comment by helkarakse** [comment]
Yes I am. You can close the issue. Thanks for the help Nallar.
